/**
 * @module Lock
 */

import type { OneOrMore, TimeSpan } from "@/utilities/_module";
import type { ILock, ILockListener } from "@/lock/contracts/lock.contract";

/**
 * @group Contracts
 */
export type LockProviderCreateSettings = {
    ttl?: TimeSpan | null;
    owner?: OneOrMore<string>;
};

/**
 * The <i>ILockProvider</i> contract defines a way for managing locks independent of the underlying technology.
 * It commes with more convient methods compared to <i>ILockAdapter</i>.
 * @group Contracts
 */
export type ILockProvider = ILockListener & {
    /**
     * The <i>create</i> method is used to create an instance of <i>{@link ILock}</i>.
     * You can provide a custom owner using the <i>settings.owner</i> field. If not specified a unique owner will be generated by default.
     * You can also provide a TTL value using the <i>settings.ttl</i> field. If not specified it defaults to null, meaning no TTL is applied.
     * @example
     * ```ts
     * import { type ILockProvider, delay, TimeSpan } from "@daiso-tech/core";
     *
     * // Asume the inputed lockProvider is empty.
     * async function main(lockProvider: ILockProvider): Promise<void> {
     *   const lock = await lockProvider.create("a");
     *
     *   // You can now use the lock as you want.
     *   await lock.acquire();
     *   console.log("Hello world");
     *   await lock.release();
     * }
     * ```
     */
    create(
        key: OneOrMore<string>,
        settings?: LockProviderCreateSettings,
    ): ILock;

    /**
     * The <i>getGroup</i> method returns the group name.
     * @example
     * ```ts
     * import type { ILockProvider } from "@daiso-tech/core";
     *
     * // Asume the inputed lockProvider is empty and the default rootGroup is "@global"
     * async function main(lockProvider: ILockProvider): Promise<void> {
     *   console.log(lockProvider.getGroup())
     *
     *   const lockProviderA = lockProvider.withGroup("a");
     *
     *   // Will be "@global/a"
     *   console.log(lockProviderA.getGroup())
     * }
     * ```
     */
    getGroup(): string;
};

/**
 * The <i>IGroupableLockProvider</i> contract defines a way for managing locks independent of the underlying technology.
 * It commes with one extra method which is useful for multitennat applications compared to <i>{@link ILockProvider}</i>.
 * @group Contracts
 */
export type IGroupableLockProvider = ILockProvider & {
    /**
     * The <i>withGroup</i> method returns a new <i>{@link ILockProvider}</i> instance that groups locks together.
     * Only locks in the same group will be acquired and released, leaving locks outside the group unaffected.
     * This useful for multitennat applications.
     * @example
     * ```ts
     * import type { IGroupableLockProvider } from "@daiso-tech/core";
     *
     * // Asume the inputed lockProvider is empty and the default rootGroup is "@global"
     * async function main(lockProvider: IGroupableLockProvider): Promise<void> {
     *   const key = "a";
     *
     *   const lockProviderA = lockProvider.withGroup("a");
     *   const lockA = lockProviderA.create(key);
     *
     *   const lockProviderB = lockProvider.withGroup("b");
     *   const lockB = lockProviderB.create(key);
     *
     *   const resultA = await lockA.acquire();
     *   const resultB = await lockB.acquire();
     *
     *   // Will print out true for both lockA.acquire() and lockB.acquire()
     *   console.log("resultA:", resultA);
     *   console.log("resultB", resultB);
     * }
     * ```
     */
    withGroup(group: OneOrMore<string>): ILockProvider;
};
